import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import heroimg from "../public/nft-header-visual.webp";
import { useRouter } from "next/navigation";
import heroimg2 from "../public/how-to-buy-nft.png";
import superfluid_logo from "../public/superfluid-logo-dark.svg";
import polygon_logo from "../public/polygon-logo.svg";
import thegraph_logo from "../public/The-Graph.png";
// import heroimg3 from "../public/nft1.png";
// import { QueryClient, QueryClientProvider, useQuery } from "react-query";

// const inter = Inter({ subsets: ["latin"] });

import Link from "next/link";
import { useEffect, useState } from "react";
import { useScrollPosition } from "@/hooks/useScrollPosition";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount } from "wagmi";

export default function Home() {
  // const scrollPosition = useScrollPosition();
  const router = useRouter();
  function classNames(...classes) {
    return classes.filter(Boolean).join(" ");
  }
  // ********** RainbowKitProvider **********
  const getNow = () => {
    if (address) {
      router.push("/profile");
    } else {
      alert("Connect your wallet first");
    }
  };

  const { address } = useAccount();
  const [showFoundAdd, setFoundAdd] = useState(false);

  return (
    <>
      <Head>
        <title>NFT Lending</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/***********  Header ***********/}

        {/* ********** Hero Section ********** */}
        <div className="min-h-[100vh] flex flex-row justify-center items-center max-w-[90vw] m-auto py-[18vh] ">
          <div className={styles.gradient1}></div>
          <div className="max-w-[50%] mr-8">
            <p className="px-8 py-1 my-4 bg-[#252A2F] mb-8 text-[#BCBFC1] max-w-max rounded-full tracking-widest font-[0.985rem]">
              Fixed-Interest NFT Lending DESK
            </p>
            <h1 className="text-[3.652rem] font-[700] leading-none">
              Unleash the Value of Your NFTs
            </h1>
            <p className="text-[#83888C] text-[1.5rem] mt-[1rem] leading-[1.4] w-4/5">
              Use your NFT as collateral to borrow fDAI, or fUSDC from lenders.
              Repay your loan and get your NFT back.
            </p>
            <div className="mt-[2rem]">
              <button
                className="relative z-[500] flex py-[1rem] px-[2rem] items-center bg-[#1E4DD8] gap-[0.5rem] whitespace-nowrap text-[1.25rem] font-[700] rounded-lg cursur-pointer"
                onClick={() => getNow()}
              >
                Get Now{" "}
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  height="24px"
                  viewBox="0 0 24 24"
                  width="24px"
                  fill="#ffffff"
                  // className="ml-2"
                >
                  <path d="M24 24H0V0h24v24z" fill="none" opacity=".87" />
                  <path d="M7.38 21.01c.49.49 1.28.49 1.77 0l8.31-8.31c.39-.39.39-1.02 0-1.41L9.15 2.98c-.49-.49-1.28-.49-1.77 0s-.49 1.28 0 1.77L14.62 12l-7.25 7.25c-.48.48-.48 1.28.01 1.76z" />
                </svg>
              </button>
            </div>
          </div>
          <div>
            <Image
              src={heroimg}
              alt="heroimage"
              className="w-[32vw] relative z-10"
            ></Image>
            <div className={styles.gradient2}></div>
            <div className={styles.gradient3}></div>
          </div>
        </div>

        {/* ********** second section ********** */}

        <div className="min-h-[100vh] m-auto py-[8rem] bg-[#ffffff] relative z-10">
          <div className="m-auto text-center">
            <h2 className="font-[700] text-[2.5rem] text-black mb-4">
              How It Works ?
            </h2>
            <div>
              <ul className="text-[#000000] grid-ul">
                <li>
                  Put down an NFT as Collateral and borrow stablecoins against
                  it.
                </li>
                <li>
                  Take one or more loans. This will pull a stream from you using
                  ACL to pay interest on your loan.
                </li>
                <li>
                  Pay any amount of your loan then the repayment transaction
                  would update your stream down
                </li>
                <li>Repay full loan amount and get your NFT back.</li>

                <li>
                  Just connect your wallet, stake your NFTs, and apply for loans
                  ; that is all. Go Now!{" "}
                </li>
              </ul>
            </div>
          </div>
        </div>
        {/* ********** third section ********** */}
        <div className=" flex flex-col justify-center items-center min-h-[80vh] p-8">
          <h1 className="m-8 text-[700] text-[2.5rem]">Powered By</h1>
          <div className="sponsers">
            <div className="bg-white rounded-xl p-4 max-w-[300px] max-h-[300px] h-[200px] flex flex-col justify-center items-center">
              <Image
                src={superfluid_logo}
                alt="superfluid"
                width="200px"
                height="150px"
                className="max-w-[100%] w-[100%] max-h-[100%] h-[100%]"
              ></Image>
            </div>
            <div className="bg-white rounded-xl p-4 max-w-[300px] max-h-[300px] h-[200px] flex flex-col justify-center items-center">
              <Image
                src={polygon_logo}
                alt="polygon"
                width="200px"
                height="150px"
                className="max-w-[100%] w-[100%] max-h-[100%] h-[100%]"
              ></Image>
            </div>
            <div className="bg-white rounded-xl p-4 max-w-[300px] max-h-[300px] h-[200px] flex flex-col justify-center items-center">
              <Image
                src={thegraph_logo}
                alt="polygon"
                width="200px"
                height="150px"
                className="max-w-[100%] w-[100%] max-h-[100%] h-[100%]"
              ></Image>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
